perf(python): upgrade pyarrow version to 15.0.0 (#2056)
<!--
**Thanks for contributing to Fury.**

**If this is your first time opening a PR on fury, you can refer to
[CONTRIBUTING.md](https://github.com/apache/fury/blob/main/CONTRIBUTING.md).**

Contribution Checklist

- The **Apache Fury (incubating)** community has restrictions on the
naming of pr titles. You can also find instructions in
[CONTRIBUTING.md](https://github.com/apache/fury/blob/main/CONTRIBUTING.md).

- Fury has a strong focus on performance. If the PR you submit will have
an impact on performance, please benchmark it first and provide the
benchmark result here.
-->

## What does this PR do?

 pip install -v -e .
Using pip 22.0.4 from
D:\code\PycharmProjects\project\venv\lib\site-packages\pip (python 3.9)
Obtaining file:///D:/code/fury/fury/python
  Running command python setup.py egg_info

  A module that was compiled using NumPy 1.x cannot be run in
  NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
  versions of NumPy, modules must be compiled with NumPy 2.0.
  Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

  If you are a user of the module, the easiest solution will be to
  downgrade to 'numpy<2' or try to upgrade the affected module.
  We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last): File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "D:\code\fury\fury\python\setup.py", line 32, in <module>
      import pyarrow as pa
File
"D:\code\PycharmProjects\project\venv\lib\site-packages\pyarrow\__init__.py",
line 65, in <module>
      import pyarrow.lib as _lib
  AttributeError: _ARRAY_API not found
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "D:\code\fury\fury\python\setup.py", line 32, in <module>
      import pyarrow as pa
File
"D:\code\PycharmProjects\project\venv\lib\site-packages\pyarrow\__init__.py",
line 65, in <module>
      import pyarrow.lib as _lib
    File "pyarrow\lib.pyx", line 36, in init pyarrow.lib
  ImportError: numpy.core.multiarray failed to import
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

note: This error originates from a subprocess, and is likely not a
problem with pip.

<!-- Describe the purpose of this PR. -->

## Related issues

<!--
Is there any related issue? Please attach here.

- #xxxx0
- #xxxx1
- #xxxx2
-->

## Does this PR introduce any user-facing change?

<!--
If any user-facing interface changes, please [open an
issue](https://github.com/apache/fury/issues/new/choose) describing the
need to do so and update the document if necessary.
-->

- [ ] Does this PR introduce any public API change?
- [ ] Does this PR introduce any binary protocol compatibility change?

## Benchmark

<!--
When the PR has an impact on performance (if you don't know whether the
PR will have an impact on performance, you can submit the PR first, and
if it will have impact on performance, the code reviewer will explain
it), be sure to attach a benchmark data here.
-->